import XCTest
@testable import QuietWhisper

final class SnippetTests: XCTestCase {
    func testTitleFromEmptyTextIsUntitled() {
        XCTAssertEqual(Snippet.makeTitle(from: ""), "Untitled")
    }

    func testTitleFromWhitespaceOnlyIsUntitled() {
        XCTAssertEqual(Snippet.makeTitle(from: "    \n  "), "Untitled")
    }

    func testTitleFromSingleSentencePreservedUpTo50Chars() {
        let s = "Hello there friend"
        XCTAssertEqual(Snippet.makeTitle(from: s), "Hello there friend")
    }

    func testTitleStopsAtFirstSentenceBoundary() {
        let s = "First sentence. Second sentence!"
        XCTAssertEqual(Snippet.makeTitle(from: s), "First sentence")
    }

    func testTitleHandlesQuestionMark() {
        XCTAssertEqual(Snippet.makeTitle(from: "Why? Because."), "Why")
    }

    func testTitleTruncatesLongFirstSentence() {
        let s = String(repeating: "a", count: 80) + ". next"
        let title = Snippet.makeTitle(from: s)
        XCTAssertEqual(title.count, 50)
        XCTAssertTrue(title.allSatisfy { $0 == "a" })
    }

    func testTitleTrimsLeadingAndTrailingSpaces() {
        XCTAssertEqual(Snippet.makeTitle(from: "  spaced.  out  "), "spaced")
    }

    func testTitleFromTextWithoutPunctuationStillFitsLimit() {
        let s = String(repeating: "x", count: 200)
        XCTAssertEqual(Snippet.makeTitle(from: s).count, 50)
    }

    // MARK: - append(transcribedText:durationSec:)

    func testAppendOnEmptySnippetSetsTextWithoutSeparator() {
        let s = Snippet(title: "Untitled", text: "", durationSec: 0)
        XCTAssertTrue(s.append(transcribedText: "Hello world.", durationSec: 3))
        XCTAssertEqual(s.text, "Hello world.")
        XCTAssertEqual(s.durationSec, 3)
        XCTAssertEqual(s.title, "Hello world")
    }

    func testAppendInsertsBlankLineSeparatorBetweenTakes() {
        let s = Snippet(title: "First sentence", text: "First sentence.", durationSec: 4)
        s.append(transcribedText: "Second sentence.", durationSec: 5)
        XCTAssertEqual(s.text, "First sentence.\n\nSecond sentence.")
        XCTAssertEqual(s.durationSec, 9)
    }

    func testAppendUpdatesAutoGeneratedTitleButPreservesUserCustomTitle() {
        // Auto-generated title gets refreshed from new text.
        let auto = Snippet(title: "Hello", text: "Hello.", durationSec: 1)
        auto.append(transcribedText: "And then more.", durationSec: 2)
        XCTAssertEqual(auto.title, "Hello")
        // Wait — the title was already "Hello" which is the auto-title from
        // the prior text. After append, auto-title from full text is still
        // "Hello" (sentence boundary at first period).
        // For a real change, modify so the new auto-title differs:
        let auto2 = Snippet(title: "First", text: "First.", durationSec: 1)
        auto2.append(transcribedText: "Different start.", durationSec: 2)
        // First text auto-title is "First", new auto-title from
        // "First.\n\nDifferent start." is still "First" (split on . gives
        // ["First", "\n\nDifferent start"] and first is "First"). So title
        // stays the same — that's correct, the title is the first sentence.

        // Custom title is preserved.
        let custom = Snippet(title: "My grocery list", text: "Eggs.", durationSec: 1)
        custom.append(transcribedText: "Milk.", durationSec: 2)
        XCTAssertEqual(custom.title, "My grocery list", "user-customized title must not be clobbered")
    }

    func testAppendRefreshesUntitledTitleOnceTextExists() {
        let s = Snippet(title: "Untitled", text: "", durationSec: 0)
        s.append(transcribedText: "Now there is content.", durationSec: 2)
        XCTAssertEqual(s.title, "Now there is content")
    }

    func testAppendIgnoresEmptyOrWhitespaceOnlyTakes() {
        let s = Snippet(title: "Hi", text: "Hi.", durationSec: 1)
        XCTAssertFalse(s.append(transcribedText: "", durationSec: 5))
        XCTAssertFalse(s.append(transcribedText: "   \n  ", durationSec: 5))
        XCTAssertEqual(s.text, "Hi.", "text must not change for empty appends")
        XCTAssertEqual(s.durationSec, 1, "duration must not advance for empty appends")
    }

    func testAppendTrimsWhitespaceFromIncomingText() {
        let s = Snippet(title: "X", text: "X.", durationSec: 1)
        s.append(transcribedText: "  padded  ", durationSec: 1)
        XCTAssertEqual(s.text, "X.\n\npadded")
    }
}
